import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { apiPostRequest } from '../lib/request';
import styles from '../styles/Home.module.css';

type ListItem = { checked: boolean; name: string };

const Home: NextPage = () => {
  const [list, setList] = useState<ListItem[]>([]);

  const onChangeName = (index: number, value: string) => {
    const newList = [...list];
    newList[index].name = value;
    setList(newList);
    apiPostRequest('/api/list-store', { list: newList });
  };

  const onDelete = (index: number) => {
    if (list.length < 2) return;
    const newList = [...list];
    newList.splice(index, 1);
    setList(newList);
    apiPostRequest('/api/list-store', { list: newList });
  };

  const onToggle = (index: number) => {
    const newList = [...list];
    newList[index].checked = !newList[index].checked;
    setList(newList);
    apiPostRequest('/api/list-store', { list: newList });
  };

  const onAdd = () => {
    const newList = [...list, { checked: false, name: '' }];
    setList(newList);
    apiPostRequest('/api/list-store', { list: newList });
  };

  const fetchList = async () => {
    try {
      const response = await apiPostRequest<{ status: 'ok'; list: ListItem[] }>('/api/list', { fix: 123 });
      if (response.status != 'ok') {
        throw new Error(`Request error ${response.status}`);
      }
      setList(response.list);
    } catch (err) {
      setList([]);
    }
  };

  useEffect(() => {
    fetchList();
    const id = setInterval(fetchList, 10000);
    return () => clearInterval(id);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Diploi Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Diploi
          <br /> <a href="https://nextjs.org">Next.js</a>+PostgreSQL
          <br /> TODO-list
        </h1>

        <div className={styles.list}>
          {list.map((l, i) => (
            <div key={i}>
              <input type="checkbox" onChange={() => onToggle(i)} checked={l.checked} />
              <input type="text" onChange={(e) => onChangeName(i, e.target.value)} value={l.name} />
              &nbsp;<button onClick={() => onDelete(i)}>X</button>
            </div>
          ))}
        </div>
        <button onClick={onAdd}>Add</button>
      </main>
    </div>
  );
};

export default Home;
